name: Test Windows Shell
on:
  workflow_dispatch:

jobs:
  explore-windows:
    runs-on: windows-latest
    steps:
      - name: PowerShell
        shell: pwsh
        run: |
          Write-Host "PowerShell"
          Write-Host $env:PATH
          Get-Command python
          python --version

          Get-Command git
          git --version

          Get-Command cmake
          cmake --version

          Get-Command rustc
          rustc --version

          Get-Command gcc
          gcc --version

          Get-Command bash
          Get-Command choco
          Get-ChildItem HKLM:\SOFTWARE | Select-Object -First 20

          Get-ChildItem HKCU:\Software | Select-Object -First 20

      - name: CMD
        shell: cmd
        run: |
          echo CMD
          echo %PATH%

      - name: Bash
        shell: bash
        run: |
          echo "Bash"
          echo "$PATH"

      - name: Python
        shell: python
        run: |
          import os
          print("Python")
          print(os.environ["PATH"])
