name: Build Windows app
on:
  workflow_dispatch:

jobs:
  explore-windows:
    runs-on: windows-latest
    steps:
      - name: Inspect OS
        run: |
          Write-Host "===== USER ====="
          whoami
          Write-Host "`n===== WINDOWS ====="
          Get-ComputerInfo |
          Select-Object WindowsProductName,
                        WindowsVersion,
                        OsArchitecture

          Write-Host "`n===== ENVIRONMENT ====="
          Write-Host "RUNNER_OS=$env:RUNNER_OS"
          Write-Host "RUNNER_ARCH=$env:RUNNER_ARCH"
